name = "default"

[prime]
side = "esc"
top = "tab"
tall = "x"
short = "mod4"

[kit]

[kit.dpad]
up = "up"
down = "down"
left = "left"
right = "right"

[knob]
press = "btn_left"
turn = "ptr_wheel_discrete(20, 1)"

[scroll]
press = "none"
turn = "none"

[dial]
press = "none"
turn = "ptr_motion(50, 0)"
