name = "Default"

[layouts]

### Example entries
# All examples assume they exist inside [layouts.?.knob].
#
## Unidirectional
#
# press = "none"
# press = { action = "none", kind = "release" }
# press = { action = "none", kind = "hold" }
#
## Bidirectional
#
# turn = { action = "none", rate = 1 }
# turn = { action = "none", reverse = "none", rate = 1 }
#

[layouts.main]

[layouts.main.prime]
side = "none"
top = "none"
tall = { action = "space", kind = "release" }
short = { action = "esc", kind = "release" }

side_x2 = "none"
top_x2 = "none"
tall_x2 = "none"
short_x2 = "none"

side_top = "none"
side_tall = "none"
side_short = "none"
top_tall = "none"
top_short = "none"
tall_short = "none"

[layouts.main.kit]
tour = "none"
up = "up"
down = "down"
left = "left"
right = "right"
c1 = "comma"
c2 = "dot"

top_up = "none"
top_down = "none"
top_left = "none"
top_right = "none"
side_up = "none"
side_down = "none"
side_left = "none"
side_right = "none"

tall_c1 = "none"
tall_c2 = "none"
short_c1 = "none"
short_c2 = "none"

[layouts.main.knob]
press = "none"
turn = "none"

side_turn = "none"
top_turn = "none"
tall_turn = "none"
short_turn = "none"

[layouts.main.scroll]
press = "none"
turn = "wheel-"

side_turn = "none"
top_turn = "none"
tall_turn = "none"
short_turn = "none"

[layouts.main.dial]
press = "none"
turn = "hwheel"

[shortcuts]

#[shortcuts.?]
#key = "none"
#shift = true
#ctrl = true
#alt = true
#super = true

[shortcuts.taskmngr]
key = "delete"
ctrl = true
alt = true

[macros]

[macros.tourbox]
[[macros.tourbox.entries]]
action = ""

[menus]

[menus.layouts]

[[menus.layouts.entries]]
func = "layout(main)"
