name = "Default"

[layouts]

### Example entries
# All examples assume they exist inside [layouts.?.knob].
#
## Unidirectional
# The default kind is 'hold'
#
# press = "none"
# press = { action = "none", kind = "hold" }
# press = { action = "none", kind = "up" }
# press = { action = "none", kind = "down" }
#
## Bidirectional
# The default rate is 1
#
# turn = { action = "none", rate = 1 }
# turn = { action = "none", reverse = "none", rate = 1 }
#

[layouts.main]

[layouts.main.prime]
side = "none"
top = "none"
tall = "space"
short = "esc"

side_x2 = "none"
top_x2 = "none"
tall_x2 = "none"
short_x2 = "none"

side_top = "none"
side_tall = "none"
side_short = "none"
top_tall = "none"
top_short = "none"
tall_short = "none"

[layouts.main.kit]
tour = "none"

up = "up"
down = "down"
left = "left"
right = "right"

top_up = "none"
top_down = "none"
top_left = "none"
top_right = "none"
side_up = "none"
side_down = "none"
side_left = "none"
side_right = "none"

c1 = "comma"
c2 = "dot"

tall_c1 = "none"
tall_c2 = "none"
short_c1 = "none"
short_c2 = "none"

[layouts.main.knob]
press = "none"
turn = "none"

tall_turn = "none"
short_turn = "none"
top_turn = "none"
side_turn = "none"

[layouts.main.scroll]
press = "none"
turn = "wheel-"

tall_turn = "none"
short_turn = "none"
top_turn = "none"
side_turn = "none"

[layouts.main.dial]
press = "none"
turn = "hwheel"

[shortcuts]

#[shortcuts.?]
#action = "none"
#shift = true
#ctrl = true
#alt = true
#super = true

[shortcuts.taskmngr]
action = "delete"
ctrl = true
alt = true

[macros]

[macros.tourbox]
[[macros.tourbox.entries]]
action = ""

[menus]

[menus.layouts]

[[menus.layouts.entries]]
func = "layout(main)"
