name = "default"

[prime]
side = "esc"
top = "tab"
tall = "space"
short = "enter"

[kit]

[kit.dpad]
up = "up"
down = "down"
left = "left"
right = "right"

[knob]
press = "none"
turn = "ptr_wheel_discrete(20, 1)"

[scroll]
press = "btn_middle"
turn = "ptr_wheel_discrete(20, 1)"

[dial]
press = "none"
turn = "ptr_hwheel_discrete(20, 1)"
