name = "test1"

[prime]
side = "b"
side_x2 = "b"
top = "b"
top_x2 = "b"
tall = "b"
tall_x2 = "b"
short = "b"
short_x2 = "b"
side_top = "b"
side_tall = "b"
side_short = "b"
top_tall = "b"
top_short = "b"
tall_short = "b"

[kit]

[kit.dpad]
up = "b"
down = "b"
left = "b"
right = "b"

[kit.side_dpad]
up = "b"
down = "b"
left = "b"
right = "b"

[kit.top_dpad]
up = "b"
down = "b"
left = "b"
right = "b"

[knob]
press = "b"
turn = "t"
side_turn = "t"
top_turn = "t"
tall_turn = "t"
short_turn = "t"

[scroll]
press = "b"
turn = "t"
side_turn = "t"
top_turn = "t"
tall_turn = "t"
short_turn = "t"

[dial]
press = "b"
turn = "t"

[layers.test.prime]
side = "b"
side_x2 = "b"
top = "b"
top_x2 = "b"
tall = "b"
tall_x2 = "b"
short = "b"
short_x2 = "b"
side_top = "b"
side_tall = "b"
side_short = "b"
top_tall = "b"
top_short = "b"
tall_short = "b"

[layers.menu]

[shortcuts]
a = { name = "A", action = "a" }
b = "b"
c = "b"

[macros.macro1]
name = "Test Macro 1"
actions = ["a", "b", "c"]

[macros.macro2]
name = "Test Macro 2"
actions = ["a", "b", "c"]

[macro_groups.macro_group1]
name = "Test Macro Group 1"
groups = [
  ["a"],
  ["b"],
  ["c"],
]

[macro_groups.macro_group2]
name = "Test Macro Group 2"
reverse = true
groups = [
  ["a"],
  ["b"],
  ["c"],
]
